# Generated by Django 5.1.1 on 2025-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.TextField()),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='static/images/')),
                ('top', models.IntegerField()),
                ('discriptions', models.CharField(max_length=1000)),
            ],
        ),
    ]
